### ISSUE TITLE
rollup ^2.0.0 compatibility

### ISSUE THREAD

**Issue by lucaelin** [asyncLiz/rollup-plugin-minify-html-literals#15]
When installing this plugin with a current rollup version, I get the following warning:
```
npm WARN rollup-plugin-minify-html-literals@1.2.5 requires a peer of rollup@^0.65.2 || ^1.0.0 but none is installed. You must install peer dependencies yourself.
```
Is it true that this plugin is incompatible with rollup ^2.0.0? It appears to be doing its job just fine.

**Comment by asyncLiz** [comment]
Sorry for the delay! The plugin should be compatible with rollup v2. https://github.com/asyncLiz/rollup-plugin-minify-html-literals/pull/17 should fix this.

**Comment by Matsuuu** [comment]
Hi! 

What's the situtation with this? I don't think there's a new release lately, and the current one still crashes on rollup above 2.0 @asyncLiz
